# xmin: -2
# xmax: 1
# ymin: 0
# ymax: 1.5
# res: 0.001
# max_step: [10, 200]
# attribute: 'escape_time'
# ---
xmin: -2
xmax: -1.3
ymin: 0
ymax: 0.1
res: 0.0005
max_step: [100]
attribute: 'escape_time'